Repository pknu-wap/2024-1_App1, pull requests merged in 2024-06, with the labels that each got.

#178 feature/165/현황페이지 수정2
  client/front/assets/images/paper-plane.png
  client/front/lib/main_post_page.dart
  client/front/lib/status_page_requesting.dart
  client/front/lib/status_page_running.dart
Labels: 기능 추가, 강민강민이강민, FRONTEND

#180 feature/179 현황페이지 websocket 연동 첫 연결
  client/.idea/libraries/Dart_Packages.xml
  client/.idea/workspace.xml
  client/front/lib/status_page_requesting.dart
  client/front/lib/status_page_running.dart
  client/front/pubspec.yaml
Labels: 기능 추가, 🐲경윤경윤민경윤 🐉, FRONTEND

#183 feature/181/웹소켓 연결 성공!
  client/.idea/libraries/Dart_Packages.xml
  client/.idea/libraries/Dart_SDK.xml
  client/.idea/workspace.xml
  client/front/lib/status_page_requesting.dart
  client/front/lib/status_page_running.dart
Labels: 기능 추가, 강민강민이강민, FRONTEND

#185 feature/168 feat 수정하기 페이지2
  client/front/lib/checkerrand.dart
  client/front/lib/fixerrand/fixerrand.dart
  client/front/lib/fixerrand/fixerrandwidget/fixdue.dart
  client/front/lib/fixerrand/fixerrandwidget/fixiscash.dart
  client/front/lib/fixerrand/fixerrandwidget/fixminimap.dart
  client/front/lib/home.dart
  client/front/lib/login.dart
  client/front/lib/main.dart
  client/front/lib/map.dart
  client/front/lib/showerrand/mainshowerrand.dart
  client/front/lib/showerrand/showerrandwidget/showerrandwidget.dart
  client/front/lib/showerrand/showerrandwidget/stamp/namelength/namelength2.dart
  client/front/lib/showerrand/showerrandwidget/stamp/namelength/namelength3.dart
  client/front/lib/showerrand/showerrandwidget/stamp/namelength/namelength4.dart
  client/front/lib/showerrand/showerrandwidget/stamp/namelength/namelength5more.dart
  client/front/lib/showerrand/showerrandwidget/stamp/stamp.dart
  client/front/lib/showerrand/showerrandwidget/tablescreen/tablescreen1.dart
  client/front/lib/showerrand/showerrandwidget/tablescreen/tablescreen2.dart
  client/front/lib/showerrand/showerrandwidget/textfieldwidget.dart
  client/front/lib/sign_up_success.dart
  client/front/lib/status_page_running.dart
  client/front/lib/writeerrand.dart
Labels: 기능 추가, 🐧수현수현김수현🐧, FRONTEND

#187 feature/184/현황페이지 버그 수정 기능 추가
  client/.idea/workspace.xml
  client/front/lib/status_page_requesting.dart
  client/front/lib/status_page_running.dart
Labels: 기능 추가, 강민강민이강민, FRONTEND

#190 feature/189 요청서 수정하기 api 연동
  client/.idea/libraries/Dart_Packages.xml
  client/.idea/libraries/Dart_SDK.xml
  client/.idea/runConfigurations/start.xml
  client/front/lib/fixerrand/fixerrand.dart
  client/front/lib/fixerrand/fixerrandwidget/fixdue.dart
  client/front/lib/fixerrand/fixerrandwidget/fixiscash.dart
  client/front/lib/fixerrand/fixerrandwidget/fixminimap.dart
Labels: 기능 추가, 🐲경윤경윤민경윤 🐉, FRONTEND

#192 feature/188 feat 보여지는 요청서 animation
  client/front/assets.lnk
  client/front/assets/fonts/SangSangShin/SangSangShin.otf
  client/front/lib/showerrand/mainshowerrand.dart
  client/front/lib/showerrand/showerrandwidget/showerrandwidget.dart
  client/front/lib/showerrand/showerrandwidget/textfieldwidget.dart
  client/front/pubspec.yaml
Labels: 기능 추가, 🐧수현수현김수현🐧, FRONTEND

#193 Feature/184/게시글 버그 수정, 디자인
  client/.idea/libraries/Dart_SDK.xml
  client/front/lib/fixerrand/fixerrand.dart
  client/front/lib/fixerrand/fixerrandwidget/fixdue.dart
  client/front/lib/fixerrand/fixerrandwidget/fixiscash.dart
  client/front/lib/home.dart
  client/front/lib/status_page_requesting.dart
  client/front/lib/status_page_running.dart
  client/front/lib/writeerrand.dart
Labels: 기능 추가, 강민강민이강민, FRONTEND

#198 feature/197 bug 각종 버그 수정
  client/front/lib/home.dart
  client/front/lib/main.dart
  client/front/lib/showerrand/mainshowerrand.dart
Labels: 버그 수정, 🐲경윤경윤민경윤 🐉, FRONTEND

#200 Feature/194 feat 보여지는 요청서 애니메이션 추가
  client/front/lib/profile.dart
  client/front/lib/showerrand/showerrandwidget/showerrandwidget.dart
  client/front/lib/showerrand/showerrandwidget/stamp/stamp.dart
  client/front/lib/showerrand/showerrandwidget/textfieldwidget.dart
Labels: 기능 추가, 🐧수현수현김수현🐧, FRONTEND

#204 Bug/203/하단바 오버레이 고치기
  client/.idea/libraries/Dart_Packages.xml
  client/.idea/libraries/Dart_SDK.xml
  client/front/lib/fixerrand/fixerrand.dart
  client/front/lib/home.dart
  client/front/lib/status_page_requesting.dart
  client/front/lib/status_page_running.dart
  client/front/lib/writeerrand.dart
  client/front/pubspec.yaml
Labels: 기능 추가, 강민강민이강민, FRONTEND

#206 feature/201 feat 디자인 수정
  client/front/android/app/src/main/res/drawable-hdpi/android12splash.png
  client/front/android/app/src/main/res/drawable-hdpi/splash.png
  client/front/android/app/src/main/res/drawable-mdpi/android12splash.png
  client/front/android/app/src/main/res/drawable-mdpi/splash.png
  client/front/android/app/src/main/res/drawable-night-hdpi/android12splash.png
  client/front/android/app/src/main/res/drawable-night-mdpi/android12splash.png
  client/front/android/app/src/main/res/drawable-night-xhdpi/android12splash.png
  client/front/android/app/src/main/res/drawable-night-xxhdpi/android12splash.png
  client/front/android/app/src/main/res/drawable-night-xxxhdpi/android12splash.png
  client/front/android/app/src/main/res/drawable-v21/background.png
  client/front/android/app/src/main/res/drawable-xhdpi/android12splash.png
  client/front/android/app/src/main/res/drawable-xhdpi/splash.png
  client/front/android/app/src/main/res/drawable-xxhdpi/android12splash.png
  client/front/android/app/src/main/res/drawable-xxhdpi/splash.png
  client/front/android/app/src/main/res/drawable-xxxhdpi/android12splash.png
  client/front/android/app/src/main/res/drawable-xxxhdpi/splash.png
  client/front/android/app/src/main/res/drawable/background.png
  client/front/android/app/src/main/res/values-night-v31/styles.xml
  client/front/android/app/src/main/res/values-v31/styles.xml
  client/front/assets/images/alert.png
  client/front/assets/images/loading_quokka_left_x4.png
  client/front/assets/images/loading_quokka_right_x4.png
  client/front/assets/images/loading_quokka_sort_x4.png
  client/front/assets/images/loding_quokka_sort.png
  client/front/assets/images/quokka2.png
  client/front/assets/images/quokka2_x4.png
  client/front/assets/images/upload_image_button.png
  client/front/flutter_native_splash.yaml
  client/front/ios/Runner/Assets.xcassets/LaunchBackground.imageset/background.png
  client/front/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
  client/front/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
  client/front/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
  client/front/ios/Runner/Base.lproj/LaunchScreen.storyboard
  client/front/lib/check_image.dart
  client/front/lib/login.dart
  client/front/lib/main.dart
  client/front/lib/profile.dart
  client/front/lib/sign_up.dart
  client/front/lib/upload_image.dart
  client/front/lib/writeerrand.dart
  client/front/web/index.html
  client/front/web/splash/img/dark-1x.png
  client/front/web/splash/img/dark-2x.png
  client/front/web/splash/img/dark-3x.png
  client/front/web/splash/img/dark-4x.png
  client/front/web/splash/img/light-1x.png
  client/front/web/splash/img/light-2x.png
  client/front/web/splash/img/light-3x.png
  client/front/web/splash/img/light-4x.png
Labels: 기능 추가, 🐧수현수현김수현🐧, FRONTEND

#207 feature/205 알림 팝업 추가
  client/front/lib/checkerrand.dart
  client/front/lib/status_page_requesting.dart
Labels: 기능 추가, 🐲경윤경윤민경윤 🐉, FRONTEND

#212 feature/211 앱 로딩화면 애니메이션 추가
  client/.idea/libraries/Dart_Packages.xml
  client/front/android/app/src/main/res/drawable-hdpi/android12splash.png
  client/front/android/app/src/main/res/drawable-hdpi/splash.png
  client/front/android/app/src/main/res/drawable-mdpi/android12splash.png
  client/front/android/app/src/main/res/drawable-mdpi/splash.png
  client/front/android/app/src/main/res/drawable-night-hdpi/android12splash.png
  client/front/android/app/src/main/res/drawable-night-mdpi/android12splash.png
  client/front/android/app/src/main/res/drawable-night-xhdpi/android12splash.png
  client/front/android/app/src/main/res/drawable-night-xxhdpi/android12splash.png
  client/front/android/app/src/main/res/drawable-night-xxxhdpi/android12splash.png
  client/front/android/app/src/main/res/drawable-v21/launch_background.xml
  client/front/android/app/src/main/res/drawable-xhdpi/android12splash.png
  client/front/android/app/src/main/res/drawable-xhdpi/splash.png
  client/front/android/app/src/main/res/drawable-xxhdpi/android12splash.png
  client/front/android/app/src/main/res/drawable-xxhdpi/splash.png
  client/front/android/app/src/main/res/drawable-xxxhdpi/android12splash.png
  client/front/android/app/src/main/res/drawable-xxxhdpi/splash.png
  client/front/android/app/src/main/res/drawable/launch_background.xml
  client/front/android/app/src/main/res/values-night-v31/styles.xml
  client/front/android/app/src/main/res/values-v31/styles.xml
  client/front/assets/images/loading_app_gif.gif
  client/front/flutter_native_splash.yaml
  client/front/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
  client/front/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
  client/front/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
  client/front/ios/Runner/Base.lproj/LaunchScreen.storyboard
  client/front/lib/login.dart
  client/front/lib/main.dart
  client/front/pubspec.yaml
  client/front/web/index.html
  client/front/web/splash/img/dark-1x.png
  client/front/web/splash/img/dark-2x.png
  client/front/web/splash/img/dark-3x.png
  client/front/web/splash/img/dark-4x.png
  client/front/web/splash/img/light-1x.png
  client/front/web/splash/img/light-2x.png
  client/front/web/splash/img/light-3x.png
  client/front/web/splash/img/light-4x.png
Labels: 기능 추가, 🐲경윤경윤민경윤 🐉, FRONTEND

#214 feature/213 현황페이지 평가페이지 뒤로가기 버그
  client/front/lib/status_page_requesting.dart
  client/front/lib/status_page_running.dart
Labels: 버그 수정, 🐲경윤경윤민경윤 🐉, FRONTEND

#216 feature/215 거리순 페이지네이션 api 추가
  server/appteam/.gitignore
  server/appteam/build.gradle
  server/appteam/src/main/java/com/pknuErrand/appteam/config/SecurityConfig.java
  server/appteam/src/main/java/com/pknuErrand/appteam/config/WebSocketConfig.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/UtilityController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/errand/ErrandController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/mail/MailController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/member/MemberController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/statusMessage/StatusMessageController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/Errand.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/ErrandBuilder.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/ErrandCompletionStatus.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/mail/VerificationCode.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/member/Member.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/statusMessage/StatusMessage.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/errand/ErrandDetailResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/errand/ErrandDistanceListResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/errand/ErrandDistancePaginationRequestVo.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/errand/ErrandListResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/errand/ErrandPaginationRequestVo.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/errand/ErrandRequestDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/errand/ErrandResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/errand/ErrandSaveRequestDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/errand/InProgressErrandListResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/member/MemberErrandDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/statusMessage/StatusMessageRequestDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/statusMessage/StatusMessageResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/repository/StatusMessageRepository.java
  server/appteam/src/main/java/com/pknuErrand/appteam/repository/errand/ErrandCompletionStatusRepository.java
  server/appteam/src/main/java/com/pknuErrand/appteam/repository/errand/ErrandRepository.java
  server/appteam/src/main/java/com/pknuErrand/appteam/repository/mail/MailMemoryRepository.java
  server/appteam/src/main/java/com/pknuErrand/appteam/repository/member/MemberRepository.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/errand/ErrandService.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/mail/MailService.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/member/MemberService.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/statusMessage/StatusMessageService.java
  server/appteam/src/test/java/com/pknuErrand/appteam/AppteamApplicationTests.java
Labels: 기능 추가, 🐲경윤경윤민경윤 🐉, BACKEND

#217 Feature/210/현황페이지 페이지 연동
  client/.idea/libraries/Dart_Packages.xml
  client/.idea/libraries/Dart_SDK.xml
  client/front/lib/home.dart
  client/front/lib/re-showmap.dart
  client/front/lib/showerrand/re-showerrand.dart
  client/front/lib/status_page_requesting.dart
  client/front/lib/status_page_running.dart
  client/front/lib/writeerrand.dart
Labels: 기능 추가, 강민강민이강민, FRONTEND

#218 feature/208 feat 팝업 메시지 디자인 수정
  client/front/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  client/front/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  client/front/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  client/front/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  client/front/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  client/front/assets/images/appIconFinal.png
  client/front/assets/images/appIconFinal_1024px.png
  client/front/assets/images/appIconFinal_x4.png
  client/front/assets/images/check.png
  client/front/assets/images/quokka_pointO.png
  client/front/assets/images/quokka_pointX.png
  client/front/flutter_launcher_icons.yaml
  client/front/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  client/front/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  client/front/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  client/front/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  client/front/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  client/front/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  client/front/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  client/front/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  client/front/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  client/front/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  client/front/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@1x.png
  client/front/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@2x.png
  client/front/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@1x.png
  client/front/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@2x.png
  client/front/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  client/front/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  client/front/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@1x.png
  client/front/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@2x.png
  client/front/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  client/front/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  client/front/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  client/front/lib/checkerrand.dart
  client/front/lib/custom_dialog.dart
  client/front/lib/home.dart
  client/front/lib/login.dart
  client/front/lib/profile.dart
  client/front/lib/sign_up.dart
  client/front/lib/status_page_requesting.dart
  client/front/lib/status_page_running.dart
Labels: 기능 추가, 🐧수현수현김수현🐧, FRONTEND

#225 feature/224 feat 글 보기 페이지 오버플로우 수정
  client/front/lib/checkerrand.dart
Labels: 기능 추가, 🐧수현수현김수현🐧, FRONTEND

#226 Bug/222/모바일 마진 동적 테스트
  client/front/lib/calculatemargin.dart
  client/front/lib/home.dart
  client/front/lib/login.dart
  client/front/lib/re-showmap.dart
  client/front/lib/writeerrand.dart
Labels: 버그 수정, 강민강민이강민, FRONTEND

#227 feature/219/svg이미지 추가
  .idea/workspace.xml
  client/front/assets/images/MainImage.svg
  client/front/assets/images/alarm_icon.svg
  client/front/assets/images/alert.svg
  client/front/assets/images/arrow_back.svg
  client/front/assets/images/bin.svg
  client/front/assets/images/check.svg
  client/front/assets/images/close_circle.svg
  client/front/assets/images/closed_eye.svg
  client/front/assets/images/dark_speech_bubble_L.svg
  client/front/assets/images/dark_speech_bubble_R.svg
  client/front/assets/images/errand.svg
  client/front/assets/images/firework.svg
  client/front/assets/images/history_icon.svg
  client/front/assets/images/home_icon.svg
  client/front/assets/images/light_speech_bubble_L.svg
  client/front/assets/images/light_speech_bubble_R.svg
  client/front/assets/images/map.svg
  client/front/assets/images/map_dest.svg
  client/front/assets/images/open_eye.svg
  client/front/assets/images/paper-plane.svg
  client/front/assets/images/party_popper.svg
  client/front/assets/images/pencil.svg
  client/front/assets/images/profile_icon.svg
  client/front/assets/images/quokka.svg
  client/front/assets/images/quokka_point_O.svg
  client/front/assets/images/quokka_point_X.svg
  client/front/assets/images/red_dot_alarm.svg
  client/front/assets/images/requesting_errand.svg
  client/front/assets/images/running_errand.svg
  client/front/assets/images/score_icon.svg
  client/front/assets/images/search_icon.svg
  client/front/assets/images/smile_quokka.svg
  client/front/assets/images/upload_image_box.svg
  client/front/assets/images/upload_image_button.svg
  client/front/assets/images/upload_image_sample.svg
  client/front/assets/images/write_icon.svg
  client/front/assets/images/₩.svg
  client/front/lib/checkerrand.dart
  client/front/lib/custom_dialog.dart
  client/front/lib/fixerrand/fixerrand.dart
  client/front/lib/home.dart
  client/front/lib/login.dart
  client/front/lib/map.dart
  client/front/lib/profile.dart
  client/front/lib/re-showmap.dart
  client/front/lib/sign_up_success.dart
  client/front/lib/status_page_requesting.dart
  client/front/lib/status_page_running.dart
  client/front/lib/upload_image.dart
  client/front/lib/writeerrand.dart
Labels: 버그 수정, 제희제희이제희, FRONTEND

#229 feature/228/svg 파일 수정,추가
  .idea/workspace.xml
  client/front/assets/images/clock.svg
  client/front/assets/images/errand_popup_quokka.svg
  client/front/assets/images/marker_small.svg
  client/front/assets/images/status_quokka.svg
  client/front/assets/images/status_smile_quokka.svg
  client/front/lib/checkerrand.dart
  client/front/lib/home.dart
  client/front/lib/status_page_requesting.dart
  client/front/lib/status_page_running.dart
Labels: 버그 수정, 제희제희이제희, FRONTEND
