Repository pknu-wap/2024-1_App1, pull requests merged in 2024-04, with the labels that each got.

#3 Feat: Errand Controller
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/errand/ErrandController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/ErrandResponseDto.java
Labels: enhancement

#15 Feature/14 errand entity 등록일 필드 추가
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/Errand.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/ErrandRequestDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/ErrandResponseDto.java
Labels: 🐲경윤경윤민경윤 🐉, BACKEND, QA

#17 Feature/16 errand entity 연관관계 재매핑
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/Errand.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/ErrandRequestDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/ErrandResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/member/Member.java
Labels: 🐲경윤경윤민경윤 🐉, BACKEND, QA

#20 Feature/18 errand 등록 시 불필요한 데이터를 받아오는 문제 해결을 위해 ErrandSaveRequestDto 추가
  server/appteam/src/main/java/com/pknuErrand/appteam/AppteamApplication.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/errand/ErrandController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/Errand.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/ErrandBuilder.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/defaultDto/ErrandRequestDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/defaultDto/ErrandResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/saveDto/ErrandSaveRequestDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/errand/ErrandService.java
Labels: 🐲경윤경윤민경윤 🐉, BACKEND, QA

#23 Feature/22 errand 목록 불러올 때 필요한 데이터 변경
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/errand/ErrandController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/getDto/ErrandListResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/member/MemberErrandDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/errand/ErrandService.java
Labels: 🐲경윤경윤민경윤 🐉, BACKEND, QA

#31 Refactor: errand 등록에 필요한 정보 수정
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/Errand.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/saveDto/ErrandSaveRequestDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/errand/ErrandService.java
Labels: 🐲경윤경윤민경윤 🐉, BACKEND, QA

#35 [FEAT] 심부름 요청 수락 시 심부름 상태 변경 및 errander 정보 update 기능
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/errand/ErrandController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/Errand.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/errand/ErrandService.java
Labels: 기능 추가, 🐲경윤경윤민경윤 🐉, BACKEND

#39 [REFACTOR] errand 관련 코드 리팩터링
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/getDto/ErrandDetailResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/getDto/ErrandListResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/errand/ErrandService.java
Labels: 🐲경윤경윤민경윤 🐉, BACKEND, 리팩터링

#41 feature/40-errand-하나-불러올-때-isMyErrand-필드-추가
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/Errand.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/defaultDto/ErrandRequestDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/defaultDto/ErrandResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/getDto/ErrandDetailResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/errand/ErrandService.java
Labels: 🐲경윤경윤민경윤 🐉, BACKEND, QA

#28 Design : 디자인 적용 및 디자인 관련 코드 수정
  .idea/workspace.xml
  client/.idea/.gitignore
  client/.idea/client.iml
  client/.idea/libraries/Dart_SDK.xml
  client/.idea/misc.xml
  client/.idea/modules.xml
  client/.idea/vcs.xml
  client/front/assets/Rectangle 1.png
  client/front/assets/Rectangle 3.png
  client/front/assets/커카.png
  client/front/lib/main.dart
  client/front/pubspec.yaml
Labels: 기능 추가, 수현수현김수현, FRONTEND

#43 Feat : 다음 페이지로 넘어가기 + 이전 화면으로 돌아가기 + 회원가입 페이지 구현
  client/.idea/workspace.xml
  client/front/assets/Vector 9.png
  client/front/lib/main.dart
  client/front/lib/sign_up.dart
Labels: 기능 추가, 수현수현김수현, FRONTEND

#46 feature/45-errand-수정-기능-추가
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/errand/ErrandController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/Errand.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/errand/ErrandService.java
Labels: 기능 추가, 🐲경윤경윤민경윤 🐉, BACKEND

#48 Feature/47 errand status 관련 기능 변경
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/Errand.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/saveDto/ErrandSaveRequestDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/errand/ErrandService.java
Labels: 🐲경윤경윤민경윤 🐉, BACKEND, QA

#50 Feature/49 errand 삭제 기능 추가
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/errand/ErrandController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/errand/ErrandService.java
Labels: 기능 추가, 🐲경윤경윤민경윤 🐉, BACKEND

#52 Feature/51 errand 정렬 및 카테고리 분류 후 페이지네이션 기능
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/errand/ErrandController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/Errand.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/ErrandBuilder.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/Sort.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/defaultDto/ErrandRequestDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/defaultDto/ErrandResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/getDto/ErrandDetailResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/getDto/ErrandListResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/getDto/ErrandPaginationRequestVo.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/saveDto/ErrandSaveRequestDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/repository/errand/ErrandRepository.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/errand/ErrandService.java
Labels: 기능 추가, 🐲경윤경윤민경윤 🐉, BACKEND

#54 Feature/21 feat 회원가입 로그인 기능 구현
  server/appteam/build.gradle
  server/appteam/src/main/java/com/pknuErrand/appteam/AppteamApplication.java
  server/appteam/src/main/java/com/pknuErrand/appteam/config/SecurityConfig.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/errand/ErrandController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/member/MemberController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/member/Member.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/member/MemberFormDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/member/MemberUserDetails.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/member/MemberUserDetailsDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/jwt/JWTFilter.java
  server/appteam/src/main/java/com/pknuErrand/appteam/jwt/JWTUtil.java
  server/appteam/src/main/java/com/pknuErrand/appteam/jwt/LoginFilter.java
  server/appteam/src/main/java/com/pknuErrand/appteam/repository/member/MemberRepository.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/errand/ErrandService.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/member/MemberService.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/member/MemberUserDetailsService.java
  server/appteam/src/main/resources/application.properties
Labels: 기능 추가, 제희제희이제희, BACKEND

#55 Feature/44 feat 6회원정보 입력 회원정보 오류
  client/front/assets/Rectangle 1.png
  client/front/assets/Rectangle 3.png
  client/front/assets/Vector 9.png
  client/front/assets/fonts/Paybooc/paybooc-Bold.otf
  client/front/assets/fonts/Paybooc/paybooc-ExtraBold.otf
  client/front/assets/fonts/Paybooc/paybooc-Light.otf
  client/front/assets/fonts/Paybooc/paybooc-Medium.otf
  client/front/assets/fonts/Pretendard/Pretendard-Black.otf
  client/front/assets/fonts/Pretendard/Pretendard-Bold.otf
  client/front/assets/fonts/Pretendard/Pretendard-ExtraBold.otf
  client/front/assets/fonts/Pretendard/Pretendard-ExtraLight.otf
  client/front/assets/fonts/Pretendard/Pretendard-Light.otf
  client/front/assets/fonts/Pretendard/Pretendard-Medium.otf
  client/front/assets/fonts/Pretendard/Pretendard-Regular.otf
  client/front/assets/fonts/Pretendard/Pretendard-SemiBold.otf
  client/front/assets/fonts/Pretendard/Pretendard-Thin.otf
  client/front/assets/fonts/Roboto/Roboto-Black.ttf
  client/front/assets/fonts/Roboto/Roboto-Bold.ttf
  client/front/assets/fonts/Roboto/Roboto-Light.ttf
  client/front/assets/fonts/Roboto/Roboto-Medium.ttf
  client/front/assets/fonts/Roboto/Roboto-Regular.ttf
  client/front/assets/fonts/Roboto/Roboto-Thin.ttf
  client/front/assets/images/close eye.png
  client/front/assets/images/image 6.png
  client/front/assets/images/open eye.png
  client/front/assets/images/커카.png
  client/front/lib/login.dart
  client/front/lib/main.dart
  client/front/lib/profile.dart
  client/front/lib/sign_up.dart
  client/front/pubspec.yaml
Labels: 기능 추가, 🐧수현수현김수현🐧, FRONTEND

#57 Feature/53/학생증 인증 기능 구현
  client/.idea/client.iml
  client/.idea/libraries/Dart_Packages.xml
  client/.idea/libraries/Dart_SDK.xml
  client/front/android/app/src/main/AndroidManifest.xml
  client/front/assets/Subtract.png
  client/front/assets/firework.png
  client/front/assets/upload_image_sample.png
  client/front/lib/checkimage.dart
  client/front/lib/signupsuccess.dart
  client/front/lib/uploadimage.dart
  client/front/linux/flutter/generated_plugin_registrant.cc
  client/front/linux/flutter/generated_plugins.cmake
  client/front/macos/Flutter/GeneratedPluginRegistrant.swift
  client/front/pubspec.lock
  client/front/pubspec.yaml
  client/front/test/widget_test.dart
  client/front/windows/flutter/generated_plugin_registrant.cc
  client/front/windows/flutter/generated_plugins.cmake
Labels: 기능 추가, 강민강민이강민, FRONTEND

#63 Fix: 1~7페이지 연결 성공
  client/.idea/misc.xml
  client/.idea/workspace.xml
  client/front/assets/images/Rectangle 1.png
  client/front/assets/images/Subtract.png
  client/front/assets/images/firework.png
  client/front/assets/images/upload_image_sample.png
  client/front/lib/check_image.dart
  client/front/lib/profile.dart
  client/front/lib/sign_up.dart
  client/front/lib/sign_up_success.dart
  client/front/lib/upload_image.dart
Labels: 버그 수정, 강민강민이강민, FRONTEND

#66 TEST git ignore 추가
  client/.idea/workspace.xml
  client/front/.gitignore
  client/front/lib/check_image.dart
  client/front/lib/upload_image.dart
Labels: 기능 추가, 강민강민이강민, FRONTEND

#70 feature/69-인가된-사용자-정보-가져오는-기능-추가
  server/appteam/src/main/java/com/pknuErrand/appteam/config/SwaggerConfig.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/errand/ErrandController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/jwt/JWTFilter.java
  server/appteam/src/main/java/com/pknuErrand/appteam/jwt/JWTUtil.java
  server/appteam/src/main/java/com/pknuErrand/appteam/jwt/LoginFilter.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/member/MemberService.java
Labels: 기능 추가, 🐲경윤경윤민경윤 🐉, BACKEND

#72 feature/71 errand service에서 member 도메인 관련 기능 수정
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/errand/ErrandController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/member/MemberController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/defaultDto/ErrandResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/errand/ErrandService.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/member/MemberService.java
Labels: 기능 추가, 🐲경윤경윤민경윤 🐉, BACKEND

#75 feature/74 custom exception 예외 관리
  server/appteam/src/main/java/com/pknuErrand/appteam/AppteamApplication.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/errand/ErrandController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/exception/CustomException.java
  server/appteam/src/main/java/com/pknuErrand/appteam/exception/CustomExceptionHandler.java
  server/appteam/src/main/java/com/pknuErrand/appteam/exception/ErrorCode.java
  server/appteam/src/main/java/com/pknuErrand/appteam/exception/ExceptionResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/jwt/JWTFilter.java
  server/appteam/src/main/java/com/pknuErrand/appteam/jwt/LoginFilter.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/errand/ErrandService.java
Labels: 기능 추가, 🐲경윤경윤민경윤 🐉, BACKEND

#78 Feat: 이메일, 닉네임 중복 확인
  server/appteam/build.gradle
  server/appteam/src/main/java/com/pknuErrand/appteam/config/SecurityConfig.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/member/MemberController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/member/Member.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/member/MemberFormDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/member/MemberUserDetails.java
  server/appteam/src/main/java/com/pknuErrand/appteam/jwt/JWTFilter.java
  server/appteam/src/main/java/com/pknuErrand/appteam/jwt/LoginFilter.java
  server/appteam/src/main/java/com/pknuErrand/appteam/repository/member/MemberRepository.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/member/MemberService.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/member/MemberUserDetailsService.java
Labels: 기능 추가, 제희제희이제희, BACKEND

#81 feature/ 값 넘기기, 비밀번호 눈 해결
  client/.idea/libraries/Dart_Packages.xml
  client/.idea/workspace.xml
  client/front/lib/check_image.dart
  client/front/lib/profile.dart
  client/front/lib/upload_image.dart
Labels: 기능 추가, 강민강민이강민, FRONTEND

#85 feature/83 feat 회원가입시 이메일 인증 기능 추가
  server/appteam/build.gradle
  server/appteam/src/main/java/com/pknuErrand/appteam/AppteamApplication.java
  server/appteam/src/main/java/com/pknuErrand/appteam/config/SecurityConfig.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/MailController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/Mail/VerificationCode.java
  server/appteam/src/main/java/com/pknuErrand/appteam/exception/ErrorCode.java
  server/appteam/src/main/java/com/pknuErrand/appteam/repository/MailMemoryRepository.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/MailService.java
  server/appteam/src/main/resources/application.properties
Labels: 기능 추가, 🐲경윤경윤민경윤 🐉, BACKEND

#87 feature/86 mailController clearMemoryStorage 기능 변경
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/MailController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/repository/MailMemoryRepository.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/MailService.java
Labels: 🐲경윤경윤민경윤 🐉, BACKEND, QA

#90 feature/88 errand email 예외 변경 알맞는 상태코드 전달
  server/appteam/src/main/java/com/pknuErrand/appteam/exception/CustomExceptionHandler.java
  server/appteam/src/main/java/com/pknuErrand/appteam/repository/errand/ErrandRepository.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/errand/ErrandService.java
Labels: 🐲경윤경윤민경윤 🐉, BACKEND, QA

#92 feature/91-심부름-정렬하여-불러오기-기능-분리
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/errand/ErrandController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/getDto/ErrandPaginationRequestVo.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/errand/ErrandService.java
Labels: 🐲경윤경윤민경윤 🐉, BACKEND, REFACTOR

#94 feature/93 api 문서화를 위한 swagger 추가 설정 및 ExceptionHandler 추가
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/MailController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/errand/ErrandController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/errand/saveDto/ErrandSaveRequestDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/exception/CustomExceptionHandler.java
  server/appteam/src/main/java/com/pknuErrand/appteam/exception/ErrorCode.java
  server/appteam/src/main/java/com/pknuErrand/appteam/exception/ExceptionResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/MailService.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/errand/ErrandService.java
Labels: 기능 추가, 🐲경윤경윤민경윤 🐉, BACKEND

#96 89 feat 회원가입 유효성 검사
  server/appteam/src/main/java/com/pknuErrand/appteam/config/SecurityConfig.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/member/MemberController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/member/Member.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/member/MemberFormDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/repository/member/MemberRepository.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/member/MemberService.java
Labels: 기능 추가, 제희제희이제희, BACKEND

#99 Feature/84 feat 추가 기능 구현
  client/front/android/gradle/wrapper/gradle-wrapper.properties
  client/front/lib/login.dart
  client/front/lib/profile.dart
  client/front/lib/sign_up.dart
Labels: 🐧수현수현김수현🐧, FRONTEND, REFACTOR

#100 Feature/82/메인 페이지 구현
  client/.idea/libraries/Dart_Packages.xml
  client/.idea/workspace.xml
  client/front/assets/images/add_icon.png
  client/front/assets/images/alarm_icon.png
  client/front/assets/images/history_icon.png
  client/front/assets/images/home_icon.png
  client/front/assets/images/human_icon.png
  client/front/assets/images/search_icon.png
  client/front/lib/check_image.dart
  client/front/lib/login.dart
  client/front/lib/main_post_page.dart
  client/front/lib/profile.dart
  client/front/lib/sign_up_success.dart
  client/front/lib/upload_image.dart
  client/front/pubspec.yaml
Labels: 기능 추가, 강민강민이강민, FRONTEND
