Repository pknu-wap/2024-1_App1, pull requests merged in 2024-05, with the labels that each got.

#103 Feature/102 feat 2회원가입 최종 수정
  client/.idea/libraries/Dart_Packages.xml
  client/.idea/workspace.xml
  client/front/android/gradle/wrapper/gradle-wrapper.properties
  client/front/assets/images/add_icon.png
  client/front/assets/images/alarm_icon.png
  client/front/assets/images/history_icon.png
  client/front/assets/images/home_icon.png
  client/front/assets/images/human_icon.png
  client/front/assets/images/search_icon.png
  client/front/lib/check_image.dart
  client/front/lib/login.dart
  client/front/lib/main_post_page.dart
  client/front/lib/profile.dart
  client/front/lib/sign_up.dart
  client/front/lib/sign_up_success.dart
  client/front/lib/upload_image.dart
  client/front/pubspec.yaml
Labels: 기능 추가, 🐧수현수현김수현🐧, FRONTEND

#105 Feat: 로그인 실패시 텍스트 출력
  client/.idea/workspace.xml
  client/front/lib/check_image.dart
  client/front/lib/login.dart
Labels: 기능 추가, 강민강민이강민, FRONTEND

#106 feature/102 feat 2회원가입 최종 수정
  client/front/lib/profile.dart
  client/front/lib/sign_up.dart
Labels: 기능 추가, 🐧수현수현김수현🐧, FRONTEND

#109 feat: 회원가입 페이지 API 연동
  client/front/lib/login.dart
  client/front/lib/sign_up.dart
Labels: 기능 추가, 🐧수현수현김수현🐧, FRONTEND

#111 feature/107 memberController Swagger 설정
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/member/MemberController.java
Labels: 기능 추가, 제희제희이제희, BACKEND

#112 feature/110 feat 회원정보 페이지 api 연동
  client/.idea/workspace.xml
  client/front/lib/check_image.dart
  client/front/lib/profile.dart
  client/front/lib/sign_up.dart
  client/front/lib/upload_image.dart
Labels: 버그 수정, 기능 추가, 🐧수현수현김수현🐧, FRONTEND

#116 feature/113 feat 회원가입 회원정보 디자인 수정
  client/front/lib/login.dart
  client/front/lib/main_post_page.dart
  client/front/lib/profile.dart
  client/front/lib/request.dart
  client/front/lib/sign_up.dart
  client/front/lib/upload_image.dart
Labels: 기능 추가, 🐧수현수현김수현🐧, FRONTEND

#121 Feature/120 websocket config 및 status entity 추가
  server/appteam/build.gradle
  server/appteam/src/main/java/com/pknuErrand/appteam/config/WebSocketConfig.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/status/Status.java
Labels: 기능 추가, 🐲경윤경윤민경윤 🐉, BACKEND

#124 Feature/122 feat 9요청서 작성
  client/front/assets/images/₩.png
  client/front/lib/login.dart
  client/front/lib/request.dart
Labels: 기능 추가, 🐧수현수현김수현🐧, FRONTEND

#127 feature/126 현황페이지 및 websocket 기능 추가
  server/appteam/src/main/java/com/pknuErrand/appteam/config/SecurityConfig.java
  server/appteam/src/main/java/com/pknuErrand/appteam/config/WebSocketConfig.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/errand/ErrandController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/mail/MailController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/statusMessage/StatusMessageController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/mail/VerificationCode.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/statusMessage/StatusMessage.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/errand/getDto/ErrandPaginationRequestVo.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/statusMessage/StatusMessageRequestDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/statusMessage/StatusMessageResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/repository/StatusMessageRepository.java
  server/appteam/src/main/java/com/pknuErrand/appteam/repository/mail/MailMemoryRepository.java
  server/appteam/src/main/java/com/pknuErrand/appteam/repository/member/MemberRepository.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/errand/ErrandService.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/mail/MailService.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/member/MemberService.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/statusMessage/StatusMessageService.java
Labels: 기능 추가, 🐲경윤경윤민경윤 🐉, BACKEND

#129 Feature/123/게시글 페이지 완성
  .github/ISSUE_TEMPLATE/-bug--이슈-제목.md
  .github/ISSUE_TEMPLATE/-feat--이슈-제목을-적어주세쿼카-.md
  .github/ISSUE_TEMPLATE/-qa--이슈제목--.md
  .github/ISSUE_TEMPLATE/qa--기능수정--템플릿.md
  .github/ISSUE_TEMPLATE/기본-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/버그-리포트-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  client/.idea/libraries/Dart_Packages.xml
  client/.idea/workspace.xml
  client/front/lib/login.dart
  client/front/lib/main_post_page.dart
  client/front/lib/profile.dart
  client/front/lib/sign_up.dart
  client/front/lib/testpage.dart
  client/front/linux/flutter/generated_plugin_registrant.cc
  client/front/linux/flutter/generated_plugins.cmake
  client/front/macos/Flutter/GeneratedPluginRegistrant.swift
  client/front/pubspec.yaml
  client/front/windows/flutter/generated_plugin_registrant.cc
  client/front/windows/flutter/generated_plugins.cmake
  server/appteam/build.gradle
  server/appteam/src/main/java/com/pknuErrand/appteam/AppteamApplication.java
  server/appteam/src/main/java/com/pknuErrand/appteam/Enum/Sort.java
  server/appteam/src/main/java/com/pknuErrand/appteam/Enum/Status.java
  server/appteam/src/main/java/com/pknuErrand/appteam/config/SecurityConfig.java
  server/appteam/src/main/java/com/pknuErrand/appteam/config/SwaggerConfig.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/MailController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/errand/ErrandController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/member/MemberController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/Mail/VerificationCode.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/Errand.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/ErrandBuilder.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/member/Member.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/member/MemberUserDetails.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/errand/defaultDto/ErrandRequestDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/errand/defaultDto/ErrandResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/errand/getDto/ErrandDetailResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/errand/getDto/ErrandListResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/errand/getDto/ErrandPaginationRequestVo.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/errand/saveDto/ErrandSaveRequestDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/member/MemberErrandDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/member/MemberFormDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/member/MemberUserDetailsDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/exception/CustomException.java
  server/appteam/src/main/java/com/pknuErrand/appteam/exception/CustomExceptionHandler.java
  server/appteam/src/main/java/com/pknuErrand/appteam/exception/ErrorCode.java
  server/appteam/src/main/java/com/pknuErrand/appteam/exception/ExceptionResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/jwt/JWTFilter.java
  server/appteam/src/main/java/com/pknuErrand/appteam/jwt/JWTUtil.java
  server/appteam/src/main/java/com/pknuErrand/appteam/jwt/LoginFilter.java
  server/appteam/src/main/java/com/pknuErrand/appteam/repository/MailMemoryRepository.java
  server/appteam/src/main/java/com/pknuErrand/appteam/repository/errand/ErrandRepository.java
  server/appteam/src/main/java/com/pknuErrand/appteam/repository/member/MemberRepository.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/MailService.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/errand/ErrandService.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/member/MemberService.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/member/MemberUserDetailsService.java
  server/appteam/src/main/resources/test.txt
Labels: 기능 추가, 강민강민이강민, FRONTEND

#132 feature/131-jwt-토큰-검증-api-추가
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/UtilityController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/errand/ErrandController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/mail/MailController.java
Labels: 기능 추가, 🐲경윤경윤민경윤 🐉, BACKEND

#137 feature/136 현황 페이지 관련 api 추가
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/statusMessage/StatusMessageController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/statusMessage/StatusMessageRequestDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/statusMessage/StatusMessageResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/repository/StatusMessageRepository.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/statusMessage/StatusMessageService.java
Labels: 기능 추가, 🐲경윤경윤민경윤 🐉, BACKEND

#139 feature/138 심부름 완료 관련 api
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/errand/ErrandController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/statusMessage/StatusMessageController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/Errand.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/ErrandCompletionStatus.java
  server/appteam/src/main/java/com/pknuErrand/appteam/repository/errand/ErrandCompletionStatusRepository.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/errand/ErrandService.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/statusMessage/StatusMessageService.java
Labels: 기능 추가, 🐲경윤경윤민경윤 🐉, BACKEND

#141 feature/140 errand의 due 필드 데이터 타입 변경
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/Errand.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/errand/ErrandBuilder.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/errand/defaultDto/ErrandRequestDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/errand/defaultDto/ErrandResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/errand/getDto/ErrandDetailResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/errand/getDto/InProgressErrandListResponseDto.java
  server/appteam/src/main/java/com/pknuErrand/appteam/dto/errand/saveDto/ErrandSaveRequestDto.java
Labels: 🐲경윤경윤민경윤 🐉, BACKEND, QA

#142 feature/125 feat 10도착지 검색
  client/front/.gitignore
  client/front/android/app/build.gradle
  client/front/android/app/src/main/AndroidManifest.xml
  client/front/assets/env/.env
  client/front/assets/images/close_circle.png
  client/front/assets/images/location.png
  client/front/lib/check_image.dart
  client/front/lib/login.dart
  client/front/lib/main.dart
  client/front/lib/map.dart
  client/front/lib/profile.dart
  client/front/lib/request.dart
  client/front/lib/sign_up.dart
  client/front/macos/Flutter/GeneratedPluginRegistrant.swift
  client/front/pubspec.yaml
  client/front/windows/flutter/generated_plugin_registrant.cc
  client/front/windows/flutter/generated_plugins.cmake
Labels: 기능 추가, 🐧수현수현김수현🐧, FRONTEND

#145 Feature/134/현황페이지디자인
  client/.idea/libraries/Dart_Packages.xml
  client/.idea/workspace.xml
  client/front/assets/images/Quo.svg
  client/front/assets/images/Quokka.png
  client/front/assets/images/red_dot_alarm.png
  client/front/lib/main.dart
  client/front/lib/main_post_page.dart
  client/front/pubspec.yaml
Labels: 기능 추가, 강민강민이강민, FRONTEND

#147 feature/144 flutter 사용자 현재 위치 기능
  client/.idea/libraries/Dart_Packages.xml
  client/.idea/libraries/Dart_SDK.xml
  client/.idea/workspace.xml
  client/front/android/app/src/main/AndroidManifest.xml
  client/front/lib/map.dart
  client/front/lib/request.dart
Labels: 기능 추가, 🐲경윤경윤민경윤 🐉, FRONTEND

#150 Feature/146 현황페이지디자인
  client/.idea/libraries/Dart_Packages.xml
  client/.idea/libraries/Dart_SDK.xml
  client/.idea/workspace.xml
  client/front/assets/images/arrow back.png
  client/front/assets/images/errand.png
  client/front/assets/images/map.png
  client/front/assets/images/requesting errand.png
  client/front/assets/images/running errand.png
  client/front/assets/images/smiley Quokka.png
  client/front/lib/main_post_page.dart
  client/front/lib/status_page.dart
  client/front/lib/testpage.dart
Labels: 기능 추가, 강민강민이강민, FRONTEND

#151 feature/130 마이페이지 평가 페이지
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/member/MemberController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/member/Member.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/member/MemberService.java
Labels: 기능 추가, 제희제희이제희, BACKEND

#154 feature/153 요청서 수락하기 api response 값 변경
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/errand/ErrandController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/errand/ErrandService.java
Labels: 🐲경윤경윤민경윤 🐉, BACKEND, QA

#157 feature/155 도착지 찾기 페이지 기능 추가
  client/.idea/libraries/Dart_Packages.xml
  client/.idea/libraries/Dart_SDK.xml
  client/.idea/workspace.xml
  client/front/assets/images/map_dest.png
  client/front/assets/images/도착.png
  client/front/lib/map.dart
  client/front/lib/request.dart
Labels: 기능 추가, 🐲경윤경윤민경윤 🐉, FRONTEND

#159 feature/158 요청서 등록 페이지 api 연동
  client/.idea/workspace.xml
  client/front/lib/request.dart
  client/front/lib/upload_image.dart
Labels: 기능 추가, 🐲경윤경윤민경윤 🐉, FRONTEND

#161 feature/160 심부름 삭제하기 api 연동
  client/.idea/workspace.xml
  client/front/lib/errand_check.dart
Labels: 기능 추가, 🐲경윤경윤민경윤 🐉, FRONTEND

#163 feature/162 학생증 이미지 업로드 중 문제 발생 시 페이지 안 넘어가지는 문제
  client/.idea/workspace.xml
  client/front/lib/upload_image.dart
Labels: 버그 수정, 🐲경윤경윤민경윤 🐉, FRONTEND

#166 feature/164 회원가입 완료 후 자동 로그인 기능
  client/.idea/workspace.xml
  client/front/lib/profile.dart
  client/front/lib/sign_up_success.dart
  client/front/lib/upload_image.dart
Labels: 버그 수정, 기능 추가, 🐲경윤경윤민경윤 🐉, FRONTEND

#167 feature/152 feat 보여지는 요청서 페이지
  client/front/assets.lnk
  client/front/assets/fonts/Cafe24Oneprettynight/Cafe24Oneprettynight.ttf
  client/front/assets/fonts/MaruBuri/MaruBuri-Bold.otf
  client/front/assets/fonts/MaruBuri/MaruBuri-ExtraLight.otf
  client/front/assets/fonts/MaruBuri/MaruBuri-Light.otf
  client/front/assets/fonts/MaruBuri/MaruBuri-Regular.otf
  client/front/assets/fonts/MaruBuri/MaruBuri-SemiBold.otf
  client/front/assets/fonts/SANGJUDajungdagam/SANGJUDajungdagam.ttf
  client/front/assets/images/Line1.png
  client/front/assets/images/Rectangle3.png
  client/front/assets/images/big_stamp.png
  client/front/assets/images/small_rectangle.png
  client/front/assets/images/stamp.png
  client/front/lib/errand_check.dart
  client/front/lib/main_post_page.dart
  client/front/lib/mainshowerrand/mainshowerrand.dart
  client/front/lib/mainshowerrand/showerrandwidget/showerrandwidget.dart
  client/front/lib/mainshowerrand/showerrandwidget/stamp.dart
  client/front/lib/mainshowerrand/showerrandwidget/stamp/namelength3.dart
  client/front/lib/mainshowerrand/showerrandwidget/stamp/namelength4.dart
  client/front/lib/mainshowerrand/showerrandwidget/stamp/namelength5more.dart
  client/front/lib/mainshowerrand/showerrandwidget/tablescreen/tablescreen1.dart
  client/front/lib/mainshowerrand/showerrandwidget/tablescreen/tablescreen2.dart
  client/front/lib/mainshowerrand/showerrandwidget/textfieldwidget.dart
  client/front/lib/profile.dart
  client/front/lib/request.dart
  client/front/lib/testpage.dart
  client/front/pubspec.yaml
Labels: 기능 추가, 🐧수현수현김수현🐧, FRONTEND

#169 feature/156 member 평가 api 수정
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/errand/ErrandController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/controller/member/MemberController.java
  server/appteam/src/main/java/com/pknuErrand/appteam/domain/member/Member.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/errand/ErrandService.java
  server/appteam/src/main/java/com/pknuErrand/appteam/service/member/MemberService.java
Labels: 기능 추가, 제희제희이제희, BACKEND

#171 feature/168 feat 수정하기 페이지
  client/front/lib/errand_check.dart
  client/front/lib/fixerrand/fixerrand.dart
  client/front/lib/mainshowerrand/mainshowerrand.dart
  client/front/lib/request.dart
Labels: 기능 추가, 🐧수현수현김수현🐧, FRONTEND

#172 Feature/165/현황페이지 만들기2
  client/.idea/libraries/Dart_Packages.xml
  client/.idea/libraries/Dart_SDK.xml
  client/.idea/workspace.xml
  client/front/assets/images/quokka_pointO.png
  client/front/assets/images/quokka_pointX.png
  client/front/assets/images/연한말풍선L.png
  client/front/assets/images/연한말풍선R.png
  client/front/assets/images/진한말풍선L.png
  client/front/assets/images/진한말풍선R.png
  client/front/lib/main_post_page.dart
  client/front/lib/status_page.dart
  client/front/lib/status_page_requesting.dart
  client/front/lib/status_page_running.dart
Labels: 기능 추가, 강민강민이강민, FRONTEND

#175 feature/174 학생증 정보 확인 페이지 버그
  client/.idea/encodings.xml
  client/.idea/libraries/Dart_Packages.xml
  client/.idea/libraries/Dart_SDK.xml
  client/.idea/workspace.xml
  client/front/lib/check_image.dart
Labels: 버그 수정, 🐲경윤경윤민경윤 🐉, FRONTEND
